# Generated by Django 3.2 on 2021-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcontent',
            name='files',
            field=models.FileField(default='', upload_to='downloads'),
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
