# Generated by Django 3.2 on 2021-04-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210426_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcontent',
            name='files',
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(default='', upload_to='downloads')),
                ('subject_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.subjectcontent')),
            ],
        ),
    ]
