# Generated by Django 3.2 on 2021-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_subjectcontent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontent',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
